# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
stages:
  - build
  - test
  - docker

build:
  stage: build
  image: node:latest
  script:
    - npm i && npm run build
  paths:
    - build/
    
    stages:
  - build
  - test

# ...

test:
  stage: test
  image: node:latest
  script:
    - npm i && npm test -- --coverage
  coverage: /All files\s*\|\s*([\d\.]+)/
  
  docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --update py-pip && pip install docker-compose
    - docker login -u gitlab-ci-token -p "eHMnGUKVhikh1uEAjMpr" "registry.gitlab.com"
    - docker-compose build
    - docker push "registry.gitlab.com/nlabbe/gitlab-workshop"
    
    
services:
  - mysql:latest
  - redis:latest
  - postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm install
   # - node ./specs/start.js ./specs/async.spec.js

test_db:
  script:
    - npm install
   # - node ./specs/start.js ./specs/db-postgres.spec.js
