stages:
  - build
  - docker

build:
  stage: build
  image: node:latest
  script:
    - npm i #&& npm run build
  artifacts:
    paths:
    - build/
    
    
docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u papengagne1997@gmail.com -p "Papiskang123456789" "registry.gitlab.com"
    - docker-compose build
    - docker push "registry.gitlab.com/architecture-logicielle/magasinnode"
    
services:
  #- mysql:latest
  #- redis:latest
  #- postgres:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test_async:
  stage: .post
  script:
    - npm install
   # - node ./specs/start.js ./specs/async.spec.js

test_db:
  stage: .post
  script:
    - npm install
   # - node ./specs/start.js ./specs/db-postgres.spec.js
