stages:
  - build
  - test
build:
  stage: build
  image: node:latest
  script:
    - npm i 
  artifacts:
  paths:
    - build/
    

test:
  stage: test
  image: node:latest
  script:
    - npm i  -- --coverage
  coverage: /All files\s*\|\s*([\d\.]+)/